
class AppConstants {
  static const List<String> stateList = [
    'Kachin',
    'Kayah',
    'Kayin',
    'Chin',
    'Sagaing',
    'Tanintharyi',
    'Bago(East)',
    'Bago(West)',
    'Magway',
    'Mandalay',
    'Mon',
    'Rakhine',
    'Yangon',
    'Shan (South)',
    'Shan (North)',
    'Shan (East)',
    'Ayeyarwady',
    'Nay Pyi Taw'
  ];
  static const List<List<String>> townshipList = [
    ['Myitkyina',
    'Waingmaw',
    'Injangyang',
    'Tanai',
    'Chipwi',
    'Tsawlaw',
    'Mohnyin',
    'Mogaung',
    'Hpakant',
    'Bhamo',
    'Shwegu',
    'Momauk',
    'Mansi',
    'Puta-O',
    'Sumprabum',
    'Machanbaw',
    'Nawngmun',
    'Khaunglanhpu'],
    ['Loikaw',
    'Demoso',
    'Hpruso',
    'Shadaw',
    'Bawlake',
    'Hpasawng',
    'Mese'],
    ['Hpa-An',
    'Hlaingbwe',
    'Hpapun',
    'Thandaunggyi',
    'Myawaddy',
    'Kawkareik',
    'Kyainseikgyi'],
    ['Falam',
    'Hakha',
    'Thantlang',
    'Tedim',
    'Tonzang',
    'Mindat',
    'Matupi',
    'Kanpetlet',
    'Paletwa'],
    ['Sagaing',
    'Myinmu',
    'Myaung',
    'Shwebo',
    'Khin-U',
    'Wetlet',
    'Kanbalu',
    'Kyunhla',
    'Ye-U',
    'Tabayin',
'Taze',
'Monywa',
'Budalin',
'Ayadaw',
'Chaung-U',
'Yinmarbin',
'Kani',
'Salingyi',
'Pale',
'Katha',
'Indaw',
'Tigyaing',
'Banmauk',
'Kawlin',
'Wuntho',
'Pinlebu',
'Kale',
'Kalewa',
'Mingin',
'Tamu',
'Mawlaik',
'Paungbyin',
'Hkamti',
'Homalin',
'Layshi',
'Lahe',
'Nanyun'],
    ['Dawei',
'Launglon',
'Thayetchaung',
'Yebyu',
'Myeik',
'Kyunsu',
'Palaw',
'Tanintharyi',
'Kawthoung',
'Bokpyin'
    ],
    ['Bago',
'Thanatpin',
'Kawa',
'Waw',
'Nyaunglebin',
'Kyauktaga',
'Daik-U',
'Shwegyin',
'Taungoo',
'Yedashe',
'Kyaukkyi',
'Phyu',
'Oktwin',
'Htantabin'
    ],
    ['Pyay',
'Paukkhaung',
'Padaung',
'Paungde',
'Thegon',
'Shwedaung',
'Thayarwady',
'Letpadan',
'Minhla',
'Okpho',
'Zigon',
'Nattalin',
'Monyo',
'Gyobingauk'
    ],
    ['Magway',
'Yenangyaung',
'Chauk',
'Taungdwingyi',
'Myothit',
'Natmauk',
'Minbu',
'Pwintbyu',
'Ngape',
'Salin',
'Sidoktaya',
'Thayet',
'Mindon',
'Kamma',
'Aunglan',
'Sinbaungwe',
'Pakokku',
'Yesagyo',
'Myaing',
'Pauk',
'Seikphyu',
'Gangaw',
'Tilin',
'Saw'],
    ['Aungmyaythazan',
'Chanayethazan',
'Mahaaungmyay',
'Chanmyathazi',
'Pyigyitagon',
'Amarapura',
'Patheingyi',
'Pyinoolwin',
'Madaya',
'Singu',
'Mogoke',
'Thabeikkyin',
'Kyaukse',
'Sintgaing',
'Myittha',
'Tada-U',
'Myingyan',
'Taungtha',
'Natogyi',
'Kyaukpadaung',
'Ngazun',
'Nyaung-U',
'Yamethin',
'Pyawbwe',
'Meiktila',
'Mahlaing',
'Thazi',
'Wundwin'],
    ['Mawlamyine',
'Kyaikmaraw',
'Chaungzon',
'Thanbyuzayat',
'Mudon',
'Ye',
'Thaton',
'Paung',
'Kyaikto',
'Bilin'],
    ['Sittwe',
'Ponnagyun',
'Mrauk-U',
'Kyauktaw',
'Minbya',
'Myebon',
'Pauktaw',
'Rathedaung',
'Maungdaw',
'Buthidaung',
'Kyaukpyu',
'Munaung',
'Ramree',
'Ann',
'Thandwe',
'Toungup',
'Gwa'],
    ['Insein',
'Mingaladon',
'Hmawbi',
'Hlegu',
'Taikkyi',
'Shwepyithar',
'Thingangyun',
'Yankin',
'South Okkalapa',
'North Okkalapa',
'Thaketa',
'Dawbon',
'Tamwe',
'Pazundaung',
'Botahtaung',
'Dagon Myothit (South)',
'Dagon Myothit (North)',
'Dagon Myothit (East)',
'Dagon Myothit (Seikkan)',
'Mingalartaungnyunt',
'Thanlyin',
'Kyauktan',
'Thongwa',
'Kayan',
'Twantay',
'Kawhmu',
'Kungyangon',
'Dala',
'Seikgyikanaungto',
'Cocokyun',
'Kyauktada',
'Pabedan',
'Lanmadaw',
'Latha',
'Ahlone',
'Kyeemyindaing',
'Sanchaung',
'Hlaing',
'Kamaryut',
'Mayangone',
'Dagon',
'Bahan',
'Seikkan',
'Hlaingtharya (East)',
'Hlaingtharya (West)'],
    ['Taunggyi',
'Nyaungshwe',
'Hopong',
'Hsihseng',
'Kalaw',
'Pindaya',
'Ywangan',
'Lawksawk',
'Pinlaung',
'Pekon'],
    ['Loilen',
'Laihka',
'Nansang',
'Kunhing',
'Kyethi',
'Mongkaing',
'Monghsu',
'Langkho',
'Mongnai',
'Mawkmai',
'Mongpan',
'Lashio',
'Hseni',
'Mongyai',
'Tangyan',
'Pangsang (Panghkam)',
'Narphan',
'Pangwaun',
'Mongmao'],
    ['Muse',
'Namhkan',
'Kutkai',
'Kyaukme',
'Nawnghkio',
'Hsipaw',
'Namtu',
'Namhsan',
'Mongmit',
'Mabein',
'Manton',
'Kunlong',
'Hopang',
'Laukkaing',
'Konkyan',
'Matman',
'Konkyan (Kokang SAZ)',
'Laukkaing (Kokang SAZ)',
'Chinshwehaw Sub-township (Kokang SAZ)',
'Nam Tit',
'Nar Wee (Na Wi)',
'Man Tun',
'Kawng Min Hsang',
'Hsawng Hpa (Saun Pha)',
'Hkun Mar (Hkwin Ma)',
'Long Htan',
'Yawng Lin',
'Lin Haw',
'Ka Lawng Hpar',
'Aik Chan (Ai\' Chun)',
'Yin Pang',
'Man Man Hseng',
'Nawng Hkit',
'Nam Hkam Wu',
'Nar Kawng',
'Pang Hkam',
'Pang Yang',
'Kengtung',
'Mongkhet',
'Mongyang',
'Mongla',
'Monghsat',
'Mongping',
'Mongton',
'Tachileik',
'Monghpyak',
'Mongyawng',
'Mong Hpen',
'Ho Tawng (Ho Tao)',
'Mong Pawk',
'Mong Kar',
'Nam Hpai'],
    ['Pathein',
'Kangyidaunt',
'Thabaung',
'Ngapudaw',
'Kyonpyaw',
'Yegyi',
'Kyaunggon',
'Hinthada',
'Zalun',
'Lemyethna',
'Myanaung',
'Kyangin',
'Ingapu',
'Myaungmya',
'Einme',
'Labutta',
'Wakema',
'Mawlamyinegyun',
'Maubin',
'Pantanaw',
'Nyaungdon',
'Danubyu',
'Pyapon',
'Bogale',
'Kyaiklat',
'Dedaye'],
    ['Zay Yar Thi Ri',
'Za Bu Thi Ri',
'Tatkon',
'Det Khi Na Thi Ri',
'Poke Ba Thi Ri',
'Pyinmana',
'Lewe',
'Oke Ta Ra Thi Ri']
  ];
  static const Map<String, List<String>> stateAndTownshipList = {
    'Kachin' : ['Myitkyina',
    'Waingmaw',
    'Injangyang',
    'Tanai',
    'Chipwi',
    'Tsawlaw',
    'Mohnyin',
    'Mogaung',
    'Hpakant',
    'Bhamo',
    'Shwegu',
    'Momauk',
    'Mansi',
    'Puta-O',
    'Sumprabum',
    'Machanbaw',
    'Nawngmun',
    'Khaunglanhpu'],
    'Kayah' : ['Loikaw',
    'Demoso',
    'Hpruso',
    'Shadaw',
    'Bawlake',
    'Hpasawng',
    'Mese'],
    'Kayin' : ['Hpa-An',
    'Hlaingbwe',
    'Hpapun',
    'Thandaunggyi',
    'Myawaddy',
    'Kawkareik',
    'Kyainseikgyi'],
    'Chin' : ['Falam',
    'Hakha',
    'Thantlang',
    'Tedim',
    'Tonzang',
    'Mindat',
    'Matupi',
    'Kanpetlet',
    'Paletwa'],
    'Sagaing' :  ['Sagaing',
    'Myinmu',
    'Myaung',
    'Shwebo',
    'Khin-U',
    'Wetlet',
    'Kanbalu',
    'Kyunhla',
    'Ye-U',
    'Tabayin',
'Taze',
'Monywa',
'Budalin',
'Ayadaw',
'Chaung-U',
'Yinmarbin',
'Kani',
'Salingyi',
'Pale',
'Katha',
'Indaw',
'Tigyaing',
'Banmauk',
'Kawlin',
'Wuntho',
'Pinlebu',
'Kale',
'Kalewa',
'Mingin',
'Tamu',
'Mawlaik',
'Paungbyin',
'Hkamti',
'Homalin',
'Layshi',
'Lahe',
'Nanyun'],
    'Tanintharyi' : ['Dawei',
'Launglon',
'Thayetchaung',
'Yebyu',
'Myeik',
'Kyunsu',
'Palaw',
'Tanintharyi',
'Kawthoung',
'Bokpyin'
    ],
    'Bago(East)' : ['Bago',
'Thanatpin',
'Kawa',
'Waw',
'Nyaunglebin',
'Kyauktaga',
'Daik-U',
'Shwegyin',
'Taungoo',
'Yedashe',
'Kyaukkyi',
'Phyu',
'Oktwin',
'Htantabin'
    ],
    'Bago(West)' : ['Pyay',
'Paukkhaung',
'Padaung',
'Paungde',
'Thegon',
'Shwedaung',
'Thayarwady',
'Letpadan',
'Minhla',
'Okpho',
'Zigon',
'Nattalin',
'Monyo',
'Gyobingauk'
    ],
    'Magway' : ['Magway',
'Yenangyaung',
'Chauk',
'Taungdwingyi',
'Myothit',
'Natmauk',
'Minbu',
'Pwintbyu',
'Ngape',
'Salin',
'Sidoktaya',
'Thayet',
'Mindon',
'Kamma',
'Aunglan',
'Sinbaungwe',
'Pakokku',
'Yesagyo',
'Myaing',
'Pauk',
'Seikphyu',
'Gangaw',
'Tilin',
'Saw'],
    'Mandalay' : ['Aungmyaythazan',
'Chanayethazan',
'Mahaaungmyay',
'Chanmyathazi',
'Pyigyitagon',
'Amarapura',
'Patheingyi',
'Pyinoolwin',
'Madaya',
'Singu',
'Mogoke',
'Thabeikkyin',
'Kyaukse',
'Sintgaing',
'Myittha',
'Tada-U',
'Myingyan',
'Taungtha',
'Natogyi',
'Kyaukpadaung',
'Ngazun',
'Nyaung-U',
'Yamethin',
'Pyawbwe',
'Meiktila',
'Mahlaing',
'Thazi',
'Wundwin'],
    'Mon' : ['Mawlamyine',
'Kyaikmaraw',
'Chaungzon',
'Thanbyuzayat',
'Mudon',
'Ye',
'Thaton',
'Paung',
'Kyaikto',
'Bilin'],
    'Rakhine' : ['Sittwe',
'Ponnagyun',
'Mrauk-U',
'Kyauktaw',
'Minbya',
'Myebon',
'Pauktaw',
'Rathedaung',
'Maungdaw',
'Buthidaung',
'Kyaukpyu',
'Munaung',
'Ramree',
'Ann',
'Thandwe',
'Toungup',
'Gwa'],
    'Yangon' : ['Insein',
'Mingaladon',
'Hmawbi',
'Hlegu',
'Taikkyi',
'Shwepyithar',
'Thingangyun',
'Yankin',
'South Okkalapa',
'North Okkalapa',
'Thaketa',
'Dawbon',
'Tamwe',
'Pazundaung',
'Botahtaung',
'Dagon Myothit (South)',
'Dagon Myothit (North)',
'Dagon Myothit (East)',
'Dagon Myothit (Seikkan)',
'Mingalartaungnyunt',
'Thanlyin',
'Kyauktan',
'Thongwa',
'Kayan',
'Twantay',
'Kawhmu',
'Kungyangon',
'Dala',
'Seikgyikanaungto',
'Cocokyun',
'Kyauktada',
'Pabedan',
'Lanmadaw',
'Latha',
'Ahlone',
'Kyeemyindaing',
'Sanchaung',
'Hlaing',
'Kamaryut',
'Mayangone',
'Dagon',
'Bahan',
'Seikkan',
'Hlaingtharya (East)',
'Hlaingtharya (West)'],
    'Shan (South)' : ['Taunggyi',
'Nyaungshwe',
'Hopong',
'Hsihseng',
'Kalaw',
'Pindaya',
'Ywangan',
'Lawksawk',
'Pinlaung',
'Pekon'],
    'Shan (North)' : ['Loilen',
'Laihka',
'Nansang',
'Kunhing',
'Kyethi',
'Mongkaing',
'Monghsu',
'Langkho',
'Mongnai',
'Mawkmai',
'Mongpan',
'Lashio',
'Hseni',
'Mongyai',
'Tangyan',
'Pangsang (Panghkam)',
'Narphan',
'Pangwaun',
'Mongmao'],
    'Shan (East)' : ['Muse',
'Namhkan',
'Kutkai',
'Kyaukme',
'Nawnghkio',
'Hsipaw',
'Namtu',
'Namhsan',
'Mongmit',
'Mabein',
'Manton',
'Kunlong',
'Hopang',
'Laukkaing',
'Konkyan',
'Matman',
'Konkyan (Kokang SAZ)',
'Laukkaing (Kokang SAZ)',
'Chinshwehaw Sub-township (Kokang SAZ)',
'Nam Tit',
'Nar Wee (Na Wi)',
'Man Tun',
'Kawng Min Hsang',
'Hsawng Hpa (Saun Pha)',
'Hkun Mar (Hkwin Ma)',
'Long Htan',
'Yawng Lin',
'Lin Haw',
'Ka Lawng Hpar',
'Aik Chan (Ai\' Chun)',
'Yin Pang',
'Man Man Hseng',
'Nawng Hkit',
'Nam Hkam Wu',
'Nar Kawng',
'Pang Hkam',
'Pang Yang',
'Kengtung',
'Mongkhet',
'Mongyang',
'Mongla',
'Monghsat',
'Mongping',
'Mongton',
'Tachileik',
'Monghpyak',
'Mongyawng',
'Mong Hpen',
'Ho Tawng (Ho Tao)',
'Mong Pawk',
'Mong Kar',
'Nam Hpai'],
    'Ayeyarwady' : ['Pathein',
'Kangyidaunt',
'Thabaung',
'Ngapudaw',
'Kyonpyaw',
'Yegyi',
'Kyaunggon',
'Hinthada',
'Zalun',
'Lemyethna',
'Myanaung',
'Kyangin',
'Ingapu',
'Myaungmya',
'Einme',
'Labutta',
'Wakema',
'Mawlamyinegyun',
'Maubin',
'Pantanaw',
'Nyaungdon',
'Danubyu',
'Pyapon',
'Bogale',
'Kyaiklat',
'Dedaye'],
    'Nay Pyi Taw' : ['Zay Yar Thi Ri',
'Za Bu Thi Ri',
'Tatkon',
'Det Khi Na Thi Ri',
'Poke Ba Thi Ri',
'Pyinmana',
'Lewe',
'Oke Ta Ra Thi Ri']
  };
  static const List<String> channelList = [
    'Clinic',
    'Mobile',
    'Hospital',
    'Home Visit'
  ];
  static const List<String> clinicList = [
    'ဆေးခန်း',
    'ကွင်းဆင်း',
    'စေတနာ့ဝန်ထမ်း'
  ];
  static const List<String> attandedList = [
    'OG/Physician',
    'Doctor',
    'Nurse',
    'Midwife',
    'HA',
    'AMW',
    'EmOCW',
    'MCHW',
    'Medic',
    'CHW',
    'TTBA/TBA',
    'Other'
  ];
  static const List<String> outcomeList = [
    'OPD',
    'Transfer to IPD',
    'Referred',
    'Dead'
  ];
  static const List<String> serviceTypeList = [
    'FP',
    'PNC',
    'GBV',
    'PAC',
    'Other MCH and SRHR related services'
  ];

  static const List<List<String>> ancTitleList = [['Sr.',
    'Date',
    'Name',
    'Age',
    'Disability',
    'IDP',
    'Gestational Week',
    'Gravida',
  ' ']];

  static const List<List<String>> deliveryTitleList = [[
    'Sr.',
    'Date',
    'Name',
    'Age',
    'Disability',
    'IDP',
    'Gestational Week',
    'Gravida',
    ' '
  ]];

  static const List<List<String>> srhTitleList = [[
    'Sr.',
    'Date',
    'Name',
    'Age',
    'Sex',
    'Disability',
    'IDP',
    'Service Type',
    ' '
  ]];

  static const List<List<String>> epiTitleList = [[
    'စဉ်',
    'ကလေး အမည်',
    'ကျား/မ',
    'မသန်စွမ်းသူ',
    'ရွှေ့ပြောင်း နေထိုင်သူ',
    'နေရပ်လိပ်စာ', ' မွေးနေ့ ',
    'ဘီစီဂျီ (BCG)',
  ' ']];

  static const List<List<String>> muacTitleList = [[
    'စဉ်',
    'ရက်စွဲ',
    'အမည်',
    ' အသက်',
    'လိင်',
    'မသန်စွမ်းသူ',
    'ရွှေေ့ပြောင်းနေထိုင်သူ',
    'ဖုန်းနံပါတ်',
    ' '
  ]];

  static const List<List<String>> pnuTitleList = [[
    'စဉ်',
    'ရက်စွဲ',
    'အမည်',
    ' အသက်',
    'လိင်',
    'မသန်စွမ်းသူ',
    'ရွှေေ့ပြောင်းနေထိုင်သူ',
    'လူနာအမျိုးအစား',
    ' '
  ]];

  static const List<List<String>> consultationTitleList = [[
    'Sr.',
    'Date',
    'Channel',
    'Truma',
    'Other Consultations',
    'U5 Pneu- monia',
    'U5 Dia- rrhoea',
    'IDP',
    ' '
  ]];

  static const List<List<String>> distributionTitleList = [[
    'Sr.',
    'Date',
    'Distribution type',
    'Beneficiary type',
    'Item 1',
    'Item 2 ',
    'Item 3',
    '# of Household',
    ' '
  ]];

  static const List<List<String>> heTitleList = [[
    'စဉ်',
    'ရက်စွဲ',
    'ဟောပြောသူအမည်',
    'ရာထူး',
    'တက်ရောက်သူအမည်',
    'အသက်',
    'ကျား/မ',
    'မသန်စွမ်းသူ (ဟုတ်/ မဟုတ်)',
    ' '
  ]];

  static const List<List<String>> referralTitleList = [[
    'စဉ်',
    'ရက်စွဲ',
    'အမည်',
    'အသက် ',
    'လိင်',
    'မသန်စွမ်းသူ (ဟုတ်/ မဟုတ်)',
    'ရွှေ့ပြောင်း နေထိုင်သူ (ဟုတ်/မဟုတ်)',
    'လွှဲပြောင်းပေးပို့ခြင်း အမျိုးအစား',
    ' '
  ]];


  //For Consultation
  static const List<String> bcgList = [
    'ပိုလီယို (OPV/bOPV)',
    'ငါးမျိုးစပ်ကာကွယ်ဆေး (Penta/ DPT-HepB-Hib)',
    'ပါးချိတ်ယောင်၊ ဝက်သက်၊ ဂျိုက်သိုး (MMR)'
  ];

  static const List<String> handoverList = [
    'Clinic',
    'Secondary care',
    'Other',
  ];

static const List<String> swellingList = [
  'N0',
  '+',
  '++',
  '+++',
  'Blank/Missing'
];

static const List<String> patientTypeList = [
  '1st time',
  'Followup',
];

static const List<String> symptomsList = [
  'အရည်မသောက်နိုင်ခြင်း/ နို့မစို့နိုင်ခြင်း',
  'မှိန်း၍နှိုးရခက်ခြင်း/ သတိလစ်ခြင်း',
  'အသက်ရှူမြန်ခြင်း',
  'အသက်ရှူသွင်းစဉ် ရင်ဘတ်အောက်ချိုင့်ဝင်ခြင်း',
  'အသက်ရှူသွင်းစဉ် လည်ချောင်းအစ်စို့သံရှိခြင်း',
  'ဝမ်းသွားစဉ်သွေးပါခြင်း',
  'ကယောင်ချောက်ချားဖြစ်ခြင်း/ ဂနာမငြိမ်ဖြစ်ခြင်း',
  'မျက်တွင်းချိုင့်ဝင်ခြင်း'
  'ရေငတ်ခြင်း/ အငမ်းမရသောက်ခြင်း',
  'ဝမ်းဗိုက်အရေပြားချက်ချင်း နဂိုနေရာပြန်ရောက်ခြင်း',
  'ဝမ်းဗိုက်အရေပြားအချိန်အနည်းငယ်အတွင်း နဂိုနေရာပြန်ရောက်ခြင်',
  'ဝမ်းဗိုက်အရေပြားအချိန်အတော်ကြာမှ နဂိုနေရာပြန်ရောက်ခြင်း',
 'ဖျားခြင်း'
];

static const List<String> typeOfDiseaseList = [
  'အလွန်ပြင်းထန်သောရောဂါ',
  'ပြင်းထန်သောနမိုးနီးယား',
  'နမိုးနီးယား',
  'နမိုးနီးယားမရှိ၊ ချောင်းဆိုးခြင်း (သို့) အအေးမိခြင်း',
  'အရည်ခမ်းခြောက်မှုရှိသော ဝမ်းပျက်ဝမ်းလျှော',
  'အရည်ခမ်းခြောက်မှုမရှိသော ဝမ်းပျက်ဝမ်းလျှော',
  'ဝမ်းကိုက်ရောဂါ',
  '၁၄ ရက်ကျော်ကြာ ဝမ်းပျက်ဝမ်းလျှောခြင်း',
  '၁၄ ရက်အောက် ဝမ်းပျက်ဝမ်းလျှောခြင်း'
];

static const List<String> treatmentList = [
  'အမောက်စီစလင် (အရည်/လုံး)',
  'ဓာတ်ဆား (ထုပ်)',
  'ဇင့်ဆာလဖိတ် (လုံး)',
  'ပါရာစီတမော (လုံး)'
];

static const List<String> distributionList = [
  'Individual',
  'Household'
];

  static const List<String> beneficiaryList = [
    'MSM',
    'SW',
    'PWID',
    'PLW',
    'Disabled',
    'Other'
  ];

  static const List<String> referralTypeList = [
    'EMOC', 'ECC', 'Disability rehabilitation',
    'Malaria', 'TB', 'HIV', 'Trauma', 'GBV', 'Emergency referral', 'Other referrals'];

  static const Map<String, List<String>> reachCollectList = {
    'RMNCH': ['ANC', 'Delivery', 'SRH'],
    'Under5': ['EPI', 'MUAC', 'Pnu&Diarr'],
    'Summary': ['Consultation','Distribution','Health Education','Referral']
  };


  static const String ancTable = "ANCTable";
  static const String deliveryTable = "DeliveryTable";
  static const String srhTable = "SRHTable";
  static const String epiTable = "EPITable";
  static const String muacTable = "MUACTable";
  static const String pnuTable = "PNUTable";

  static const String consultationTable = "consultationTable";
  static const String distributionTable = "distributionTable";
  static const String healthTable = "healthTable";
  static const String referralTable = "referralTable";
}